"""Helpers for CSV artifacts generated by analyzers."""
from __future__ import annotations

import csv
import pathlib
from dataclasses import dataclass
from typing import Iterable, Mapping, Sequence


@dataclass
class CsvArtifact:
    """Represents a single CSV file to be written and optionally uploaded."""

    name: str
    headers: Sequence[str]
    rows: Iterable[Mapping[str, object]]
    table: str | None = None


def build_artifact_name(database: str, table: str) -> str:
    """Return a standardized artifact filename for a database table."""

    return f"fits.db.{database}.{table}.csv"


def write_csv(artifact: CsvArtifact, output_dir: pathlib.Path) -> pathlib.Path:
    """Write a CSV artifact to *output_dir* and return the file path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / artifact.name
    with path.open("w", newline="", encoding="utf-8-sig") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=list(artifact.headers))
        writer.writeheader()
        for row in artifact.rows:
            writer.writerow(row)
    return path
